#Site settings

# SEO settings
title: CFS 44 Timetable
author: Committee on World Food Security (CFS)
email: cfs@fao.org
description: > # this means to ignore newlines until "baseurl:"
  Website of the 44th Session of the Commitee on World Food Security
keywords: United Nations, Food Security, Nutrition, Committee on World Food Security, CFS

# Author settings
author:
    name:            Committee on World Food Security
    facebook:         UN.CFS
    twitter:          UN_CFS
    github:           UNCFS
    medium:           UN_CFS

# Timezones
timezone:           Europe/Rome

# SASS settings
sass:
  sass_dir: sass
  style: compressed


plugins:
  - jekyll-email-protect
